version: '3.8'

services:
  # Laravel App
  app:
    build:
      context: ./backend/api
      dockerfile: Dockerfile
    image: jsmuguard-app
    container_name: jsmuguard-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./backend/api:/var/www
    networks:
      - jsmuguard-network

  # Web Server (Nginx)
  webserver:
    image: nginx:alpine
    container_name: jsmuguard-nginx
    restart: unless-stopped
    ports:
      - "80:80"  # Expose to port 80 on the server
    volumes:
      - ./backend/api:/var/www
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - jsmuguard-network

  # Database (MySQL)
  db:
    image: mysql:8.0
    container_name: jsmuguard-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password
    volumes:
      - dbdata:/var/lib/mysql
    # No ports exposed to host to keep it secure, only accessible via network
    networks:
      - jsmuguard-network

  # PhpMyAdmin (Optional - for database management)
  pma:
    image: phpmyadmin/phpmyadmin
    container_name: jsmuguard-pma
    restart: unless-stopped
    links:
      - db:db
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - jsmuguard-network

networks:
  jsmuguard-network:
    driver: bridge

volumes:
  dbdata:
